ALTER TABLE `clients` ADD `groupID` SMALLINT UNSIGNED NOT NULL DEFAULT '1' AFTER `clientID` ;

CREATE TABLE IF NOT EXISTS `client_groups` (
  `groupID` smallint(5) unsigned NOT NULL auto_increment,
  `group_name` varchar(150) NOT NULL,
  `discount_rate` decimal(2,2) NOT NULL,
  PRIMARY KEY  (`groupID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;

INSERT INTO `client_groups` VALUES(1, 'Genel Müşteriler', 0.00);

ALTER TABLE `queue` CHANGE `status` `status` ENUM( 'inprocess', 'pending', 'pending-cron', 'pending-payment', 'completed', 'error', 'scheduled' )  NOT NULL DEFAULT 'pending'; 

ALTER TABLE `clients` CHANGE `phone` `phone` VARCHAR( 30 ) NOT NULL , CHANGE `cell` `cell` VARCHAR( 30 ) NOT NULL;

DROP TABLE IF EXISTS `countries`;
CREATE TABLE IF NOT EXISTS `countries` (
  `country` varchar(128) NOT NULL,
  `country_code` varchar(2) NOT NULL,
  `calling_code` varchar(64) NOT NULL,
  `calling_code_regex` varchar(255) NOT NULL,
  `calling_code_mask` varchar(30) NOT NULL,
  `default` enum('0','1') NOT NULL default '0',
  UNIQUE KEY `code` (`country_code`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


INSERT INTO `countries` (`country`, `country_code`, `calling_code`, `calling_code_regex`, `calling_code_mask`, `default`) VALUES
('Afghanistan', 'AF', '93', '', '', '0'),
('Albania', 'AL', '355', '', '', '0'),
('Algeria', 'DZ', '213', '', '', '0'),
('Angola ', 'AO', '244', '', '', '0'),
('Antarctica', 'AQ', '672', '', '', '0'),
('Argentina', 'AR', '54', '', '', '0'),
('Armenia ', 'AM', '374', '', '', '0'),
('Aruba', 'AW', '297', '', '', '0'),
('Australia ', 'AU', '61', '', '', '0'),
('Austria', 'AT', '43', '', '', '0'),
('Azerbaijan', 'AZ', '994', '', '', '0'),
('Bahrain', 'BH', '973', '', '', '0'),
('Bangladesh', 'BD', '880', '', '', '0'),
('Belgium', 'BE', '32', '', '', '0'),
('Belize', 'BZ', '501', '', '', '0'),
('Benin', 'BJ', '229', '', '', '0'),
('Bhutan', 'BT', '975', '', '', '0'),
('Bolivia ', 'BO', '591', '', '', '0'),
('Bosnia & Herzegovina ', 'BA', '387', '', '', '0'),
('Botswana ', 'BW', '267', '', '', '0'),
('Brazil ', 'BR', '55', '', '', '0'),
('Brunei Darussalam', 'BN', '673', '', '', '0'),
('Bulgaria', 'BG', '359', '', '', '0'),
('Burkina Faso ', 'BF', '226', '', '', '0'),
('Burundi', 'BI', '257', '', '', '0'),
('Cameroon', 'CM', '237', '', '', '0'),
('Canada', 'CA', '1', '', '', '0'),
('Cape Verde Islands', 'CV', '238', '', '', '0'),
('Central African Republic', 'CF', '236', '', '', '0'),
('Chad ', 'TD', '235', '', '', '0'),
('Chile ', 'CL', '56', '', '', '0'),
('China (PRC)', 'CN', '86', '', '', '0'),
('Christmas Island', 'CX', '61-8', '', '', '0'),
('Cocos-Keeling Islands', 'CC', '61', '', '', '0'),
('Colombia ', 'CO', '57', '', '', '0'),
('Comoros', 'KM', '269', '', '', '0'),
('Congo', 'CG', '242', '', '', '0'),
('Congo, Dem. Rep. (former Zaire) ', 'CD', '243', '', '', '0'),
('Cook Islands', 'CK', '682', '', '', '0'),
('Costa Rica', 'CR', '506', '', '', '0'),
('Cote d''Ivoire (Ivory Coast)', 'CI', '225', '', '', '0'),
('Croatia', 'HR', '385', '', '', '0'),
('Cuba', 'CU', '53', '', '', '0'),
('Curacao', 'CW', '599', '', '', '0'),
('Cyprus', 'CY', '357', '', '', '0'),
('Czech Republic', 'CZ', '420', '', '', '0'),
('Denmark', 'DK', '45', '', '', '0'),
('Djibouti', 'DJ', '253', '', '', '0'),
('Ecuador ', 'EC', '593', '', '', '0'),
('Egypt', 'EG', '20', '', '', '0'),
('El Salvador', 'SV', '503', '', '', '0'),
('Eritrea', 'ER', '291', '', '', '0'),
('Estonia', 'EE', '372', '', '', '0'),
('Ethiopia', 'ET', '251', '', '', '0'),
('Falkland Islands (Malvinas)', 'FK', '500', '', '', '0'),
('Faroe Islands', 'FO', '298', '', '', '0'),
('Fiji Islands', 'FJ', '679', '', '', '0'),
('Finland', 'FI', '358', '', '', '0'),
('France', 'FR', '33', '', '', '0'),
('Gambia', 'GM', '220', '', '', '0'),
('Georgia', 'GE', '995', '', '', '0'),
('Germany', 'DE', '49', '', '', '0'),
('Ghana ', 'GH', '233', '', '', '0'),
('Gibraltar ', 'GI', '350', '', '', '0'),
('Greece ', 'GR', '30', '', '', '0'),
('Greenland ', 'GL', '299', '', '', '0'),
('Guadeloupe', 'GP', '590', '', '', '0'),
('Guatemala ', 'GT', '502', '', '', '0'),
('Guinea-Bissau ', 'GW', '245', '', '', '0'),
('Guinea', 'GN', '224', '', '', '0'),
('Guyana', 'GY', '592', '', '', '0'),
('Haiti ', 'HT', '509', '', '', '0'),
('Honduras', 'HN', '504', '', '', '0'),
('Hong Kong', 'HK', '852', '', '', '0'),
('Hungary ', 'HU', '36', '', '', '0'),
('Iceland', 'IS', '354', '', '', '0'),
('India', 'IN', '91', '', '', '0'),
('Indonesia', 'ID', '62', '', '', '0'),
('Iran', 'IR', '98', '', '', '0'),
('Iraq', 'IQ', '964', '', '', '0'),
('Ireland', 'IE', '353', '', '', '0'),
('Israel ', 'IL', '972', '', '', '0'),
('Italy ', 'IT', '39', '', '', '0'),
('Japan ', 'JP', '81', '', '', '0'),
('Jordan', 'JO', '962', '', '', '0'),
('Kazakhstan', 'KG', '7', '', '', '0'),
('Kenya', 'KE', '254', '', '', '0'),
('Kiribati ', 'KI', '686', '', '', '0'),
('Korea (North)', 'KP', '850', '', '', '0'),
('Korea (South)', 'KR', '82', '', '', '0'),
('Kuwait ', 'KW', '965', '', '', '0'),
('Latvia ', 'LV', '371', '', '', '0'),
('Lebanon', 'LB', '961', '', '', '0'),
('Lesotho', 'LS', '266', '', '', '0'),
('Liberia', 'LR', '231', '', '', '0'),
('Libya', 'LY', '218', '', '', '0'),
('Liechtenstein', 'LI', '423', '', '', '0'),
('Lithuania ', 'LT', '370', '', '', '0'),
('Luxembourg', 'LU', '352', '', '', '0'),
('Macao', 'MO', '853', '', '', '0'),
('Macedonia (Former Yugoslav Rep of.)', 'MK', '389', '', '', '0'),
('Madagascar', 'MG', '261', '', '', '0'),
('Malawi ', 'MW', '265', '', '', '0'),
('Malaysia', 'MY', '60', '', '', '0'),
('Maldives', 'MV', '960', '', '', '0'),
('Mali Republic', 'ML', '223', '', '', '0'),
('Malta', 'MT', '356', '', '', '0'),
('Marshall Islands', 'MH', '692', '', '', '0'),
('Martinique', 'MQ', '596', '', '', '0'),
('Mauritania', 'MR', '222', '', '', '0'),
('Mauritius', 'MU', '230', '', '', '0'),
('Mexico', 'MX', '52', '', '', '0'),
('Moldova ', 'MD', '373', '', '', '0'),
('Monaco', 'MC', '377', '', '', '0'),
('Mongolia ', 'MN', '976', '', '', '0'),
('Montenegro', 'ME', '382', '', '', '0'),
('Morocco', 'MA', '212', '', '', '0'),
('Mozambique', 'MZ', '258', '', '', '0'),
('Myanmar', 'MM', '95', '', '', '0'),
('Namibia', 'NA', '264', '', '', '0'),
('Nauru', 'NR', '674', '', '', '0'),
('Nepal ', 'NP', '977', '', '', '0'),
('Netherlands', 'NL', '31', '', '', '0'),
('New Caledonia', 'NC', '687', '', '', '0'),
('New Zealand', 'NZ', '64', '', '', '0'),
('Nicaragua', 'NI', '505', '', '', '0'),
('Niger', 'NE', '227', '', '', '0'),
('Nigeria', 'NG', '234', '', '', '0'),
('Niue', 'NU', '683', '', '', '0'),
('Norfolk Island', 'NF', '672', '', '', '0'),
('Norway ', 'NO', '47', '', '', '0'),
('Oman', 'OM', '968', '', '', '0'),
('Pakistan', 'PK', '92', '', '', '0'),
('Palau', 'PW', '680', '', '', '0'),
('Palestinian Settlements', 'PS', '970', '', '', '0'),
('Papua New Guinea', 'PG', '675', '', '', '0'),
('Paraguay', 'PY', '595', '', '', '0'),
('Peru', 'PE', '51', '', '', '0'),
('Philippines', 'PH', '63', '', '', '0'),
('Poland', 'PL', '48', '', '', '0'),
('Portugal', 'PT', '351', '', '', '0'),
('Qatar', 'QA', '974', '', '', '0'),
('Romania', 'RO', '40', '', '', '0'),
('Russia', 'RU', '7', '', '', '0'),
('Rwandese Republic', 'RW', '250', '', '', '0'),
('St. Helena', 'SH', '290', '', '', '0'),
('St. Pierre & Miquelon', 'PM', '508', '', '', '0'),
('Samoa', 'WS', '685', '', '', '0'),
('San Marino', 'SM', '378', '', '', '0'),
('Sao Tome and Principe', 'ST', '239', '', '', '0'),
('Saudi Arabia', 'SA', '966', '', '', '0'),
('Senegal ', 'SN', '221', '', '', '0'),
('Serbia', 'RS', '381', '', '', '0'),
('Seychelles Republic', 'SC', '248', '', '', '0'),
('Sierra Leone', 'SL', '232', '', '', '0'),
('Singapore', 'SG', '65', '', '', '0'),
('Slovak Republic', 'SK', '421', '', '', '0'),
('Slovenia ', 'SI', '386', '', '', '0'),
('Solomon Islands', 'SB', '677', '', '', '0'),
('South Africa', 'ZA', '27', '', '', '0'),
('Spain', 'ES', '34', '', '', '0'),
('Sri Lanka', 'LK', '94', '', '', '0'),
('Sudan', 'SD', '249', '', '', '0'),
('Suriname ', 'SR', '597', '', '', '0'),
('Swaziland', 'SZ', '268', '', '', '0'),
('Sweden', 'SE', '46', '', '', '0'),
('Switzerland', 'CH', '41', '', '', '0'),
('Syria', 'SY', '963', '', '', '0'),
('Taiwan', 'TW', '886', '', '', '0'),
('Tajikistan', 'TJ', '992', '', '', '0'),
('Tanzania', 'TZ', '255', '', '', '0'),
('Thailand', 'TH', '66', '', '', '0'),
('Timor Leste', 'TL', '670', '', '', '0'),
('Tokelau', 'TK', '690', '', '', '0'),
('Tonga Islands', 'TO', '676', '', '', '0'),
('Tunisia', 'TN', '216', '', '', '0'),
('Turkiye', 'TR', '90', '^\\d{3} \\d{3} \\d{2} \\d{2}', '999 999 99 99', '1'),
('Turkmenistan ', 'TM', '993', '', '', '0'),
('Tuvalu', 'TV', '688', '', '', '0'),
('Uganda', 'UG', '256', '', '', '0'),
('Ukraine', 'UA', '380', '', '', '0'),
('United Arab Emirates', 'AE', '971', '', '', '0'),
('United Kingdom', 'GB', '44', '', '', '0'),
('United States of America', 'US', '1', '', '', '0'),
('Uruguay', 'UY', '598', '', '', '0'),
('Uzbekistan', 'UZ', '998', '', '', '0'),
('Vanuatu', 'VU', '678', '', '', '0'),
('Vatican City', 'VA', '39', '', '', '0'),
('Venezuela', 'VE', '58', '', '', '0'),
('Vietnam', 'VN', '84', '', '', '0'),
('Yemen', 'YE', '967', '', '', '0'),
('Zambia ', 'ZM', '260', '', '', '0'),
('Zimbabwe ', 'ZW', '263', '', '', '0');
